"""probe4 -- the committed negative corpus, run against the Python verifier
(C.5.4).

A positive vector proves a verifier can AGREE. It does not prove the verifier
is CHECKING: a function that returned its input unread would pass every
positive vector in the set. Each case here takes an honest record, changes
exactly one thing, and requires a refusal.

WHAT CHANGED, AND WHY IT MATTERS. These cases used to be fifteen lambdas in
this file. That made "Forge refuses a reordered binding" and "the browser
refuses a reordered binding" two similar claims about two separately
constructed records, which is precisely the shape of agreement that can be
true of two implementations that have both drifted. They now live in
`projection-negative-vectors.json`, which the JS conformance suite reads too,
so both are held to THE SAME BYTES.

AN ASYMMETRY WORTH STATING RATHER THAN GLOSSING. That file was generated by
`gen_negative_vectors.py`, which uses this same verifier -- so this probe is a
GOLDEN-FILE check, not an independent one. Its value is that it goes red when
`wrl_projection.py` later drifts away from bytes that are pinned; it is not
evidence that the corpus is correct. The independent check is the JS side,
which has never run any of this code. Both are needed and neither substitutes
for the other.

Two classes are worth naming.

  * The reordered bindings. Every id in the list stays correct and every
    binding stays individually true; only the ORDER lies. Order is derived
    from the semantic artifact, so the canonical bytes catch it -- but nothing
    that checked bindings as a SET would.

  * The rounding attempt. A receiver whose reader narrows a 2^63-1 rotor lane
    does not silently admit a different world; it computes a different world
    id and is refused. The exactness rule is not only about fidelity, it is
    about what an inexact peer is able to claim.

Run from a COPY of forge/:  PYTHONDONTWRITEBYTECODE=1 python3 probe4.py
"""
import json
import os
import sys

sys.dont_write_bytecode = True

import vector_files
import wrl_projection as P

HERE = os.path.dirname(os.path.abspath(__file__))

passed = 0
failed = 0


def ok(name, cond, detail=""):
    global passed, failed
    if cond:
        passed += 1
        print("  ok   %-42s %s" % (name, detail))
    else:
        failed += 1
        print("  FAIL %-42s %s" % (name, detail))


def admits(name, wire):
    global passed, failed
    try:
        P.verify_runtime_projection(wire)
        passed += 1
        print("  ok   %-42s admitted" % name)
    except Exception as e:  # noqa
        failed += 1
        print("  FAIL %-42s refused: %s" % (name, e))


def main():
    global failed

    # The copies are pinned by digest -- see vector_files. A stale copy is not
    # a red here, it is a probe that agrees with bytes nobody sends.
    try:
        ndoc = vector_files.load("_negative_vectors.json")
        bases = {v["name"]: v["wire"]
                 for v in vector_files.load("_vectors.json")["vectors"]}
    except vector_files.StaleVectorFile as e:
        print("  FAIL %-42s %s" % ("the-committed-corpus", e))
        print("\n0 passed, 1 failed")
        return 1

    print("control\n")
    # The honest records must still be ADMITTED. Without this, a verifier that
    # refused everything would score a perfect run on the corpus below.
    admits("the-untouched-record", bases["named-relations"])
    admits("the-untouched-bigint-record", bases["bigint-rotor"])

    print("\nthe committed tampers\n")

    ok("the-corpus-is-the-expected-set",
       ndoc.get("vector_set") == "wrl.projection-negative-vectors.1"
       and len(ndoc["vectors"]) >= 12,
       "%s, %d vectors" % (ndoc.get("vector_set"), len(ndoc["vectors"])))

    agree = 0
    for vec in ndoc["vectors"]:
        name = vec["name"]
        base = bases.get(vec["base"])

        # THE FIXTURE GATE, BEFORE THE VERDICT. A tamper that did not change
        # the bytes is a broken fixture, and a broken fixture must be a named
        # red rather than a verdict about the code under test. The first
        # version of this file wrote a duplicate key by replacing
        # `{"projection_version"` -- and the keys on this wire are sorted, so
        # the replace matched nothing and the case handed the verifier the
        # HONEST record and demanded a refusal. It failed loudly, which was
        # luck: the same mistake pointed the other way is a negative test that
        # passes while asserting nothing, and that one has cost me twice.
        if base is None:
            ok(name, False, "unknown base %r" % vec["base"])
            continue
        if vec["wire"] == base:
            ok(name, False, "BROKEN FIXTURE: equals its base")
            continue

        try:
            P.verify_runtime_projection(vec["wire"])
        except P.ProjectionError as e:
            code = getattr(e, "code", "?")
            # The refusal is the assertion. The CODE is compared and reported,
            # because whether a code is normative is still open -- so this
            # prints evidence for that question instead of presuming it.
            same = code in vec["refusal_codes"]
            agree += 1 if same else 0
            ok(name, True, code if same
               else "%s (corpus says %s)" % (code, vec["refusal_codes"]))
        except Exception as e:  # noqa
            # A refusal in the wrong vocabulary is how the exactness defect
            # hid: it was loud, and it said WRL_NUMERIC_RANGE about a number
            # that was in range. An UNTYPED one is worse.
            ok(name, False, "untyped %s: %s" % (type(e).__name__, e))
        else:
            ok(name, False, "ADMITTED")

    n = len(ndoc["vectors"])
    print("\n  %d/%d refusals in the vocabulary the corpus records" % (agree, n))

    print("\n%d passed, %d failed" % (passed, failed))
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
